### ISSUE TITLE
Update components to use React hooks

### ISSUE THREAD

**Issue by nitaliano** [react-native-mapbox-gl/maps#1]
We should update all of our components to move away from class based components to function based and they should use the React hooks API

**Comment by sfratini** [comment]
Aren't we forcing people to update their React/RN packages if we do this? Hooks are in v16.8.0 so people are forced to update to RN 0.59. I am not sure a lot of packages are ready to run on 0.59. Maybe we should wait a few RN releases so every package has time to catch up. 

https://github.com/facebook/react-native/issues/21967

**Comment by ferdicus** [comment]
Just my 2 cents

@sfratini: I don't know about this argument. You're basically validating people not updating their dependencies - which people should be doing.

Everyone else should be using previous versions of this lib, 
just like they apparently do with their other dependencies.

**Comment by sfratini** [comment]
@ferdicus Most of the issues I have had in the past are related to one module asking for a specific version of a module and then others not ready to be upgraded (because let's face it, most people have a lot of modules in their project) and RN usually has a lot of breaking changes, specially in 0.59. 

When creating a module I don't think we should be thinking about people only hacing Mapbox in their project...it is a whole ecosystem. So supporting only the latest RN version creates a lot of issues and barriers to new users. Specially when Hooks is a new pattern and does not add any specific feature to the framework. aka it is not needed. I do love hooks tho, and I'd love to use them, I just don't feel a lot of modules are ready for 0.59. 

Also, I am not saying people should not update. What I am saying is that if we use a feature that is only available in 0.59 then everyone needs to use that one.

**Comment by slaivyn** [comment]
> We should update all of our components to move away from class based components to function based and they should use the React hooks API

You could pave this long road without forcing the RN upgrade using [Recompose](https://github.com/acdlite/recompose), React Hooks "parent" which still can do much than Hooks.
(I am replacing all class based components in all my active projects :) )
