### ISSUE TITLE
Version 8.1.0 not published to npm

### ISSUE THREAD

**Issue by lucasfronza** [react-native-mapbox-gl/maps#1126]
Hey there!

Any reason why version 8.1.0 is not on npm?
Also, we've tried upgrading with `"@react-native-mapbox-gl/maps": "react-native-mapbox-gl/maps#8.1.0",`, but it then fails to find a compatible pod for `Mapbox-iOS-SDK`. Is that the reason why it is not yet on npm?

Thanks!

**Comment by ferdicus** [comment]
We are aware of the issue and working on it. 
This is due to the fact that travis changed it's OSS policies in the last few days. 

As for finding compatible `Mapbox-iOS-SDK` pod. 
Not sure what the issue there is - have specified a different version in the podspec?

If so, are you aware of the new install steps that come with mapbox-ios-sdk 6+


Closing this, feel free to add a clarifying comment about the iOS thing here though and open another one if you can't find a matching closed issue in the repo


Thanks.

**Comment by lucasfronza** [comment]
OK!

Will have a look at the mapbox-ios-sdk 6+ steps.

Thanks for the quick reply!

**Comment by mfazekas** [comment]
8.1.0-rc10 is now released with github actions, we'll release final release soon

**Comment by Gp2mv3** [comment]
Do you have news about the publication of the final release?
