### ISSUE TITLE
Flash when changing styleURL because it loads MapboxGL.StyleURL.Street before

### ISSUE THREAD

**Issue by hexadecy** [react-native-mapbox-gl/maps#1405]
**Describe the bug**  
When changing the styleURL it loads MapboxGL.StyleURL.Street before.
The issue is that we see the Street style flashing and it's more visible when zoomed out.

**To Reproduce**  
1. Set the **mapStyle** to `MapboxGL.StyleURL.Satellite`.
2. then switch to a custom URL like: `${Config.SERVER}/api/mapboxStyle`.
3. Before the custom URL style is loaded you will see the MapView will default to `MapboxGL.StyleURL.Street`.

Example:
```jsx
<MapboxGL.MapView styleURL={mapStyle}>
```

**Expected behavior**  
Load a default color like black during loading.

**Actual behavior**  
It will always load the MapboxGL.StyleURL.Street when no data yet and we cannot change it.

**Screenshots**  
https://user-images.githubusercontent.com/10960108/122078184-65cdb500-cdca-11eb-8408-71202b8868ef.mp4

**Versions:**  
Platform: [Android, iOS]
Platform OS: [Android 9, iOS 14.5]
Device: [Samsung S8, iPhone 11]
Emulator/ Simulator: [same issue]
Dev OS: [OSX BigSur]
react-native-mapbox-gl Version [8.2.0-beta2]
Mapbox-iOS-SDK [6.0.0]
mapbox-android-sdk [9.3.1]
React Native Version [0.63.4]

**Possible solution**  
Possibility to change the default to 'none' or set a color during the loading (Android: foregroundLoadColor).

**Comment by ferdicus** [comment]
Hi there, thanks for opening a ticket, unfortunately I was not able to reproduce this  - maybe I did it wrong though 🤷🏿 

Here my setup:
* Within our `example` app, we have a screen `example/src/examples/Map/ShowMap.tsx`
* in there we can switch between various mapbox styles
* in there I snuck in a HERE style `https://assets.vector.hereapi.com/styles/berlin/day/mapbox/tilezen?apikey=<APIKEY>`
* randomly, instead of loading the selected mapbox style, it would load the HERE style
* on physical device for Android/ on sim for iOS


https://user-images.githubusercontent.com/26439946/122564721-f82dbd00-d045-11eb-861f-f2187c194394.mp4


https://user-images.githubusercontent.com/26439946/122564812-1398c800-d046-11eb-9842-219a958a0c1a.mp4


Maybe you could share your code with us?

**Comment by ferdicus** [comment]
Hi there, thanks for opening a ticket, unfortunately I was not able to reproduce this  - maybe I did it wrong though 🤷🏿 

Here my setup:
* Within our `example` app, we have a screen `example/src/examples/Map/ShowMap.tsx`
* in there we can switch between various mapbox styles
* in there I snuck in a HERE style `https://assets.vector.hereapi.com/styles/berlin/day/mapbox/tilezen?apikey=<APIKEY>`
* randomly, instead of loading the selected mapbox style, it would load the HERE style
* on physical device for Android/ on sim for iOS


https://user-images.githubusercontent.com/26439946/122564721-f82dbd00-d045-11eb-861f-f2187c194394.mp4

Maybe you could share your code with us?

**Comment by hexadecy** [comment]
With React-Native 0.63.x we often see the MapboxGL.StyleURL.Street for 1 second before loading the correct styleURL.
But I cannot reproduce it with the demo either. (RN 0.64.1)
Also, the issue goes away after the update to React 17 and React-Native 0.64.2

**Comment by ferdicus** [comment]
> With React-Native 0.63.x we often see the MapboxGL.StyleURL.Street for 1 second before loading the correct StyleURL.
> But I cannot reproduce it with the demo either. (RN 0.64.1)
> Also, the issue goes away after the update to React 17 and React-Native 0.64.2

Alright, weird - in any case, can we close this then?

**Comment by hexadecy** [comment]
The issue is still present, but the transition is much faster with the new version (0.64).
I have to use the Network Link Conditioner to 3G to see the blue water from an ocean of the default Style URL.

I think we'll live with it.

The two possibles solutions are probably worse:
1- expose the defaultStyleURL to be changed to nothing
2- preload our styleURL and push it as JSON instead
