### ISSUE TITLE
[discussion] Camera + defaultSettings alternative

### ISSUE THREAD

**Issue by mattijsf** [react-native-mapbox-gl/maps#200]
I was wondering if we could re-think the use of `defaultSettings` added with https://github.com/react-native-mapbox-gl/maps/pull/132:

> In a lot of cases we'd just want to define where the map camera should be initially and later we'd follow user's location, or just let the user change camera, by pinch-zoom etc.

What if we track only the changes made on the `<Camera />` positioning props (`bounds`, `heading`, `pitch` `centerCoordinate `, `zoomLevel`, `padding` etc) and only apply them initially + when the values change. That could still allow us to set the initial camera and enable `followUserLocation`. Any future interacted / imperative change to the camera are kept (and disables follow mode). Until the positioning props are updated, only then we modify the camera.

Maybe I don't fully get the implications yet but I feel that the Camera API is currently somewhat confusing in this aspect.

_Note: I'm not sure if this is the best way to start this discussion. I also considered commenting in the closed PR itself. Let me know if I should do it differently._

**Comment by mfazekas** [comment]
I agree that the Camera api is confusing, and adding defaultSettings might not have helped the situation.

If i understand correctly, you propose, to update `Camera` when `center` etc. changes even when `followUserMode` is set. I think it's reasonable. Not sure if for the intitial camera settings we'd use the animationDuration or not.

One usecase supported by defaultSettings is starting out with a location and then instantly zooming to a specific location with some animationDuration/effect. But i don't think this usecase is significant enough.

`defaultSetting` was really modelled after `TextInput`-s `defaultValue`, but since `Camera` s not really a [controlled component](https://reactjs.org/docs/forms.html#controlled-components) this is not really required. My issue with `Camera` is that it looks like a controlled component, but it's not. I also really don't like the `triggerKey` workaround in `Camera`, which let's you recenter the camera with uncanged properties after user might have used pinch and zoom to change the coords. I think most application will just forget to use `triggerKey` and be broken in case user wants to renavigate to the same location (no real props change).

In our projets i prefer to use`defaultSettings` and procedural `flyTo` etc api, as i find that the cleanest. But sure if we fix `Camera` to work when followUserMode is set, then we'd be fine with that.

**Comment by arnaudambro** [comment]
If I may, I have been struggling for a few time why the method `handleRegionDidChange` did return different coordinates the first time it was loaded than the one I was giving in `centerCoordinate` props. Now I discover that it is because the init coordinates are not in `centerCoordinate` prop, but in `defaultSettings` prop. 

IMO it is not the best: the `centerCoordinate` props should also be the init coordinates, and afterwards we change the center coordinates of the map with the `flyTo` method or equivalent or by changing the `centerCoordinate` props.

**Comment by alburdette619** [comment]
If I could add, this is completely unclear as to how to use.  I set the properties as they were with `centerCoordinate` and `zoomLevel` on the Camera and every load was zooming from Africa.  Then I saw this and problem solved.  I see what you're going for here though, but why not just use the settings set initially on the component as the defaults?

**Comment by mfazekas** [comment]
>  for a few time why the method `handleRegionDidChange` did return different coordinates the first time it was loaded than the one I was giving in `centerCoordinate` props.

@arnaudambro I guess that's because the `animationDuration` which defaults to 2000. I assume, what you propose is that for centerCoordinate, etc should not apply animationDuration for the initial settings.

**Comment by arnaudambro** [comment]
@mfazekas well I think the steps are the following, tell me if I am wrong:

1. when the component mounts, it checks what is the value of the prop `defaultSettings > centerCoordinates`. If there is a value, it takes it, if not it takes the default, which seems to be something close to `[0,0]` as far as I experienced.
2. the method `handleRegionDidChange` is called
3. the `centerCoordinate` prop is taken into account, and the map goes to that given coordinates
4. the method `handleRegionDidChange` is called again

So if I am right with the above steps, instead of being too complicated with the `animationDuration` set to 0 for the first `centerCoordinate` I would really suggest to remove those `defaultSettings` and use the init props as `defaultSettings`. Easy and simple, like it was working before, isn't it ?

**Comment by mfazekas** [comment]
> * when the component mounts, it checks what is the value of the prop `defaultSettings > centerCoordinates`. If there is a value, it takes it, if not it takes the default, which seems to be something close to `[0,0]` as far as I experienced.
> 
> * the method `handleRegionDidChange` is called
> 
> * the `centerCoordinate` prop is taken into account, and the map goes to that given coordinates
`centerCoordinates` are applied after 
> 
> * the method `handleRegionDidChange` is called again



Not quite:

- when component created it uses whatever defaults the native component uses. 
- If `defaultSettings` is set we create a camera stop from that and move to there immediately without any animation. 
- we construct a camera stop from `centerCoordinate`, `animationDuration` etc. and apply it.
- on component update we don't rerender see [Camera#shouldComponentUpdate](https://github.com/react-native-mapbox-gl/maps/blob/1e886177dd0d10640628734b94a13f28e5d7ed76/javascript/components/Camera.js#L117-L119) use componentWillReceiveProps to figure out if camera config changed we create a new camera stop and pass to native layer.

https://github.com/react-native-mapbox-gl/maps/blob/1e886177dd0d10640628734b94a13f28e5d7ed76/javascript/components/Camera.js#L409-L445

**Comment by cesar3030** [comment]
I'm also facing some issues with the current implementation of the Camera API.

What I need to do is to center the map on user's location when the map loads then when the user clicks on a shape (from a ShapeSource), the maps recenter itself at the shape's coordinates.

To be able to do that, I have to first render the map with the camera's props `followUserLocation=true` , then when the user clicks on a shape I store the coordinates of the shape and re-render the map with the camera's props `followUserLocation=false` and `centerCoordinate={[lng, lat]}`. The issue with this implementation is that I still need to do a this.camera.moveTo([lng, lat]) even if `centerCoordinate={[lng, lat]}`.

The problem is that I need to re-render the camera component with `followUserLocation=false` to be able to use `this.camera.moveTo([lng, lat])`.

I wish the next implementation will allow using `this.camera.moveTo([lng, lat])` even if `followUserLocation=true`.
