### ISSUE TITLE
Deprecated texture mode is used by default on Android

### ISSUE THREAD

**Issue by janicduplessis** [react-native-mapbox-gl/maps#212]
**Describe the bug**
The Android implementation defaults to using textureMode (https://github.com/react-native-mapbox-gl/maps/blob/master/javascript/components/MapView.js#L227) which is deprecated according to https://docs.mapbox.com/android/api/map-sdk/5.0.2/com/mapbox/mapboxsdk/maps/MapboxMapOptions.html#textureMode-boolean-

Not sure if there is a reason for it.

**To Reproduce**
N/A

**Expected behavior**
Use GL map by default

**Screenshots**
N/A

**Versions (please complete the following information):**
 - Platfrom: Android
 - Device: Emulator
 - OS: Any
 - SDK Version ?
 - React Native Version 0.59

**Additional context**
N/A

**Comment by kristfal** [comment]
The reason for using textureView is that you cant have overlapping surface views in a single activity. Due to this, nesting multiple surface view maps with a JS based navigator such as react-navigation would not work. 

Since surface views do perform better, we tried making surface view default about a year ago, but got a lot of bug reports with the issues mentioned above. Because of this, we reverted and made surface view opt in. 

I’m not sure how we should handle this issue tbh. I’ll open a ticket upstream later.

**Comment by janicduplessis** [comment]
@kristfal Thanks for the explanation. I think I don't have multiple map screens in my app currently so I didn't hit this issue.

Something like react-native-screens can also help.

Seems reasonable to keep the default like this for now since you have to know what you are doing to enable surface views.
