### ISSUE TITLE
_runNativeCommand called with wrong arguments

### ISSUE THREAD

**Issue by doomsower** [react-native-mapbox-gl/maps#326]
**Describe the bug**
On Android I'm getting warning that `TypeError: args.unshift is not a function`. 

I investigated, and and found that `NativeBridgeComponent` calls `_runNativeCommand` with three arguments [here](https://github.com/react-native-mapbox-gl/maps/blob/395689e085e7922fa016eac1ff67388d6d424da3/javascript/components/NativeBridgeComponent.js#L44) in `_runPendingNativeCommands`.

`MapView` overrides `_runNativeCommand` [here](https://github.com/react-native-mapbox-gl/maps/blob/395689e085e7922fa016eac1ff67388d6d424da3/javascript/components/MapView.js#L467) and will treat nativeRef as args, which is wrong.

I'm using latest master branch.

**To Reproduce**

Not needed, as the bug us clearly in the code.

**Expected behavior**

**Screenshots**

**Versions (please complete the following information):**
 - Platfrom: [e.g. Android, iOS]
 - SDK Version [e.g. 22]
 - React Native Version [e.g. 0.59]

**Additional context**

**Comment by mfazekas** [comment]
@doomsower thanks, i guess that what #272 was talking about. Yep this overload thing is messy at best. It needs to be untagled.

**Comment by ShepelE** [comment]
Hi!
maps/javascript/components/NativeBridgeComponent:64
it accepts the args, but args is not an array, it's a similar structure and it doesn't have unshift method
so change the block to:

`
      if (isAndroid()) {
        // https://github.com/react-native-mapbox-gl/maps/issues/326
        // TypeError: args.unshift is not a function
        // fix: args is not an array, so need to perform it into real array
        const _args = [];
        for (let i=0; i<args.length; i++) {
          _args.push(args[i]);
        }

        return new Promise(resolve => {
          callbackIncrement += 1;
          const callbackID = `${methodName}_${callbackIncrement}`;
          this._addAddAndroidCallback(callbackID, resolve);
          _args.unshift(callbackID);
          runNativeCommand(this._nativeModuleName, methodName, nativeRef, _args);
        });
      }
`

**Comment by makirby** [comment]
It's a bit confusing but the `this` in `NativeBridgeComponent` is the MapView instance when the `_runPendingNativeCommands` function is called (On Mapview `setNativeRef`). So when [this](https://github.com/react-native-mapbox-gl/maps/pull/308/files#diff-215b7dde35e7c70e080a4008e7089203R44) function is run, the `_runNativeCommand` in MapView is called instead, which means the `nativeRef` is passed as the second argument instead of 'args', meaning the call ends up being `runNativeCommand(methodName, nativeRef, nativeRef)`.

The change here https://github.com/react-native-mapbox-gl/maps/pull/308/files#diff-215b7dde35e7c70e080a4008e7089203L8 seemed to cause this to happen, I'm assuming its something to to with the closure rather than just inheriting from `NativeBridgeComponent` directly.

**Comment by mfazekas** [comment]
> The change here https://github.com/react-native-mapbox-gl/maps/pull/308/files#diff-215b7dde35e7c70e080a4008e7089203L8 seemed to cause this to happen, I'm assuming its something to to with the closure rather than just inheriting from `NativeBridgeComponent` directly.

I don't think it's that change is the cause. It was called with 3 args before.

**Comment by mfazekas** [comment]
But in any case we'd need a fix like #272

**Comment by makirby** [comment]
> I don't think it's that change is the cause. It was called with 3 args before.

Not the method in NativeBridge, the method in MapView is the one that gets called as it has the same name as the one in NativeBridge, though the MapView one only takes 2 args. If you revert NativeBridge back to a plain class, instead of a function, it works.

**Comment by mfazekas** [comment]
> > I don't think it's that change is the cause. It was called with 3 args before.
> 
> Not the method in NativeBridge, the method in MapView is the one that gets called as it has the same name as the one in NativeBridge, though the MapView one only takes 2 args. If you revert NativeBridge back to a plain class, instead of a function, it works.

Yep, my understanding is that the issue is because 
1.) `NativeBridgeComponent#_runPendingCommand` calls `this._runNativeCommand(name,nativeRef,args)`
2.) Map view overrides `_runNativeCommand(methodname, nativeRef, args)` with `_runNativeCommand(name, args)`, but doesn't overrides `_runPendingCommand` which still calls the 3 arg version.

The class refactoring was just  `class NativeBridgeComponent extends React.Component  { ... }` vs `function NativeBridgeComponent(base) { return class extends base {...} }` i don't think it relates to the above issue.

**Comment by makirby** [comment]
Yeah apologies the class work makes no difference. Yeah that's the flow that II observed when I was debugging this the other day.

I went with a simple rename patch just like #272 which is running in production for us now.
