### ISSUE TITLE
App Crashes After Upgrade to 7.0.6 When RasterSource is called.

### ISSUE THREAD

**Issue by systemlevel** [react-native-mapbox-gl/maps#444]
**Describe the bug**
The Mapbox map was working fine on version 7.0.4.  I upgraded to 7.0.6 and the map started crashing.  

I isolated the crashing to this code. When I remove this RasterSource map loads fine again:

```
        <Mapbox.RasterSource
          id="poles"
          tileSize={512}
          url="https://img.nj.gov/imagerywms/Natural2015?bbox={bbox-epsg-3857}&format=image/png&service=WMS&version=1.1.1&request=GetMap&srs=EPSG:3857&transparent=true&width=256&height=256&layers=Natural2015"

        >
          <Mapbox.RasterLayer id='polesLayer' sourceID='poles'/>
        </Mapbox.RasterSource>
```

**To Reproduce**
Steps to reproduce the behavior

Upgrade to 7.0.6 and use existing RasterSource layers.  Map will crash. 

**Expected behavior**
After upgrade the map should work with WMS RasterSource layers as expected.

**Screenshots**
**Versions (please complete the following information):**

    "@react-native-mapbox-gl/maps": "^7.0.6",
 - React Native Version 0.59.9

**Additional context**

I noticed after the upgrade the following TileSource libraries were added to iOS.  Was this changed so that the WMS services don't work with the existing RasterSource way of showing those layers?

<img width="612" alt="Screen Shot 2019-10-02 at 2 37 59 PM" src="https://user-images.githubusercontent.com/894983/66080079-94d2c300-e522-11e9-8a9d-d88d773e609d.png">

**Comment by systemlevel** [comment]
@mattijsf We are using RasterSource to load WMS layers into our map.  Did the updates recently to the tileURL's, etc. effect the way to load a WMS layer?  It now crashes after the upgrade to 7.0.6

I'm thinking you might have some insight into why this is occurring. Related to this commit in anyway?  https://github.com/react-native-mapbox-gl/maps/commit/e8cca4d74b33927171291ef6430889bb690ec73f

**Comment by systemlevel** [comment]
I downgraded to "@react-native-mapbox-gl/maps": "7.0.4",  and the RasterSource WMS calls work again.  No crashing.  Something changed in version 7.0.5 and up that is creating an issue.

**Comment by systemlevel** [comment]
@mattijsf I'm thinking it's this commit https://github.com/react-native-mapbox-gl/maps/commit/e8cca4d74b33927171291ef6430889bb690ec73f but I could be wrong.  @kristfal Is there documentation we should be updating to be able to use WMS services after version 7.0.4?  Right now the existing method of loading a WMS service is broken.

**Comment by mattijsf** [comment]
Can you try it using: 

```jsx
tileUrlTemplates=["https://img.nj.gov/imagerywms/Natural2015?bbox={bbox-epsg-3857}&format=image/png&service=WMS&version=1.1.1&request=GetMap&srs=EPSG:3857&transparent=true&width=256&height=256&layers=Natural2015"]`
```

I moved tile url endpoints to `tileUrlTemplates` on all sources in order to be consistent with the official Mapbox native SDK's and provide consistent functionality across various tile bases sources:

`url`: URL to TileJSON configuration file
`tileUrlTemplates`: One or more urls pointing tile endpoints 

To make sure it wouldn't break existing sources I added backwards compatibility when a tile endpoint is used inside `url`. However it seems that I have misses some templates like yours: `{bbox-epsg-3857}`

The docs for tile sources such as `RasterSource` have already been updated but a deprecation warning should have been appeared for you which is something I should fix in a new PR. Can you confirm if the above change made it work again?
