### ISSUE TITLE
[Android] Camera issues at initialization

### ISSUE THREAD

**Issue by atomheartother** [react-native-mapbox-gl/maps#55]
**Describe the bug**
A few things seem wrong with the camera at initialization at the moment, when trying to make it start at certain `centerCoordinates`:
- The camera always starts at coordinates [0,0]
- If I set a `minZoomValue`on the camera, it never moves from [0, 0]
- Otherwise the camera moves to the given `centerCoordinates` after a short delay

**To Reproduce**
Simply use these properties for camera and mapview:
```js
      <Mapbox.MapView style={{ flex: 1 }}>
        <Mapbox.Camera centerCoordinate={[2.6, 43.1]} zoomLevel={8.5} />
      </Mapbox.MapView>
```
The camera will start at [0.0] then jump to the given centerCoordinates after a while. If you set a minZoomLevel (Such as `minZoomLevel={8}`), the camera will remain at [0, 0].

**Expected behavior**
The camera should start at the centerCoordinates. Giving it a minZoomLevel should not force it to remain stuck where it is.

**Versions (please complete the following information):**
 - Platfrom: Android
 - Device: Samsung s7
 - OS: `9.0`
 - SDK Version: `7.3.2`
 - React Native Version `0.59.8`

**Comment by systemlevel** [comment]
I am getting this issue on android as well.

**Comment by mfazekas** [comment]
@atomheartother you can use `animationDuration` to change the time it takes to move to the given location. 

I think the best would a  separate `initialCenterCoordinate`, etc. And probably the updates are better left to be done via 'ref'-s. Since the user can adjust camera parmeters with  gestures, either we'll provide procedural api-s va ref-s for updates or implement a controlled approach (like inputs in react). I have a feeling that implementing the controlled approach is significant work. 
The current approach looks good, but has significant holes like this.
