### ISSUE TITLE
Like an UserLocation use to be ShapeSource.

### ISSUE THREAD

**Issue by mertozylmz** [react-native-mapbox-gl/maps#554]
Hi, How can I move smooth for ShapeSource ? 
Like an UserLocation. Because UserLocation changed location I can see smoothly moving. 
But I can't do it for ShapeSource.

**Comment by ferdicus** [comment]
hey there,
have you checked out [Annotations](https://github.com/react-native-mapbox-gl/maps/blob/master/javascript/components/annotations/Annotation.js) and [AnimatedPoint](https://github.com/react-native-mapbox-gl/maps/blob/master/javascript/utils/AnimatedPoint.js)

Because that's how `UserLocation` is implemented. 

Should give you some pointers as to how to implement it for arbitrary ShapeSources

**Comment by mertozylmz** [comment]
Hi, @ferdicus. Thank you for feedback. I will check them and try.

**Comment by mertozylmz** [comment]
@ferdicus I listened to you and tried. It's working. But I don't know if I'm using it right. If you know the right way, would you share it with me?

**Comment by ferdicus** [comment]
Hey @mertozylmz, glad it worked - I only know it from that file.

Never implemented it myself, however I'd bet, that other would appreciate it, 
if you would share your solution here, for anyone having the same question in the future :)

**Comment by mertozylmz** [comment]
This code is available. If you want see moving animation, just change coordinate. :)
```
import Annotation from '@react-native-mapbox-gl/maps/javascript/components/annotations/Annotation';

import userIcon from './user.png';

...
<MapboxGL.Images images={{ userIcon }} />
<Annotation id='user-annotation' animated={true} coordinates={coords}>
     <MapboxGL.SymbolLayer id='user-icon' style={mapStyles.userIcon} />
</Annotation>
...

const mapStyles = {
     userIcon: {
          iconImage: 'userIcon',
          iconRotationAlignment: 'map',
          iconAllowOverlap: true,
          iconIgnorePlacement: true
     }
}
```
