### ISSUE TITLE
Can't update Camera minZoomLevel dynamically

### ISSUE THREAD

**Issue by dancherb** [react-native-mapbox-gl/maps#597]
If the minZoomLevel prop is changed after the camera has loaded, it doesn't take effect unless the whole Camera component is reloaded and reset.
```

<Mapbox.Camera
                        ref={ref => this.cameraRef = ref}
                        animationMode="moveTo"
                        animationDuration={3000}
                        minZoomLevel={limitZoom ? 7 : 2}
                        maxZoomLevel={18}
/>
```

Update: this also seems to apply to maxBounds and likely other props that might be good to update dynamically.

Android
React Native: 0.61.5
@react-native-mapbox-gl/maps: 7.0.4

**Comment by kristfal** [comment]
Thanks for reporting. This is a good first PR.

**Comment by ferdicus** [comment]
valid issue, go away stalebot

**Comment by RobertSasak** [comment]
I would like to make PR. Can you please explain me briefly how to fix it?

**Comment by mfazekas** [comment]
@RobertSasak  i think it's because:

https://github.com/react-native-mapbox-gl/maps/blob/fd4e030210ad126bdf0e36c66526a1b855a063ea/javascript/components/Camera.js#L162-L164

so we turn off normal update by react and we use

https://github.com/react-native-mapbox-gl/maps/blob/fd4e030210ad126bdf0e36c66526a1b855a063ea/javascript/components/Camera.js#L158-L160

to do the updates, and `minZoomLevel` is propbably not handled

**Comment by Ashkan-Oliaie** [comment]
I'm having this issue ,on 10% of times it is working but not at 90% , I'm not sure about how :D

**Comment by RobertSasak** [comment]
I guess it is because 10% of the time your map component is completely rerendering. minZoomLevel works on first mounting of the component. 
I still do have a plan to make a PR.

**Comment by unpxre** [comment]
Hello, I'm still facing this issue on version 8.6.0-beta.0.
