### ISSUE TITLE
Issue with maxBounds properties in iOS.

### ISSUE THREAD

**Issue by DhavalKakadiya** [react-native-mapbox-gl/maps#642]
I am using maxBounds properties in a <MapboxGL.Camera /> for set restrict scroll event on a map. But when I am using that, the zoom feature is not working on iOS. 
In android it's working fine, that's issue happens only in iOS.

Can you please help me resolve that issue?

Thanks for the help in advance!!

**Comment by DhavalKakadiya** [comment]
Anyone can help me?

**Comment by mattijsf** [comment]
I can confirm this issue using the following sample code:

```jsx
<MapboxGL.MapView style={StyleSheet.absoluteFill} styleURL={AppConfig.MAPBOX_STYLE_URL}>
  <MapboxGL.Camera
    centerCoordinate={[4.899836, 52.371411]}
    zoomLevel={14}
    maxBounds={{
      ne: [4.883025, 52.387548],
      sw: [4.919735, 52.363865],
    }}
  />
</MapboxGL.MapView>
```

@DhavalKakadiya Please include a more context or sample code when reporting issues / bugs next time. 

I can have a quick look to see what is going on on iOS.

**Comment by mattijsf** [comment]
Please make sure you use sw / ne coordinate bounds. Like the above sample I entered nw / sw coordinates in `maxBounds` I suspect you did the same.

The reason that this is working on Android is because the way handles the incoming bounds:
https://github.com/react-native-mapbox-gl/maps/blob/35dca20a24e51d28b61f151758a450958cdca390/android/rctmgl/src/main/java/com/mapbox/rctmgl/components/camera/RCTMGLCameraManager.java#L60
https://github.com/react-native-mapbox-gl/maps/blob/79a4e56bba93df87985bb953d5c2ae90861816dc/android/rctmgl/src/main/java/com/mapbox/rctmgl/utils/GeoJSONUtils.java#L185

In that second link the nw/sw are corrected into sw/ne coordinates pairs.

Let me know if this is fixes your issue.

**Comment by DhavalKakadiya** [comment]
@mattijsf, Thanks for the reply. Yes, I used same code as you send above. 
So, you said that in iOS it'll not work zoom feature if using with maxBounds property?
