### ISSUE TITLE
layerIndex Property Throws Error/Not Adding Layers In Correct Order

### ISSUE THREAD

**Issue by systemlevel** [react-native-mapbox-gl/maps#66]
**Describe the bug**
Using layerIndex property in layers does not appear to be working and throws an error.

**To Reproduce**
Steps to reproduce the behavior

```
        {loading ? null : (<Mapbox.RasterSource id="rasterSourceBasemap" tileSize={256} url={Url}>
          <Mapbox.RasterLayer
            id="basemap"
            sourceID="rasterSourceBasemap"
            style={{ rasterOpacity: 1 }}
            layerIndex={1}
          />
        </Mapbox.RasterSource>)}

        {loading ? null : (<Mapbox.ShapeSource>
          <Mapbox.SymbolLayer 
            id="guz" 
            style={{ visibility: (layers.guz.show ? "visible" : "none") }}
            layerIndex={10}
          />
        </Mapbox.ShapeSource>)}
```

**Expected behavior**
The layers would show in the order of the defined layerIndex.

**Screenshots**
I get the following error:

<img width="584" alt="Screen Shot 2019-05-29 at 1 31 24 AM" src="https://user-images.githubusercontent.com/894983/58538217-e1dc0c80-81b1-11e9-9982-f94c00cf5d18.png">

At times when the error is not present the layers don't seem to respond to the actual layerIndex defined in each layer.

**Versions (please complete the following information):**
 - Platfrom: iOS
 - React Native Version 0.59

**Comment by systemlevel** [comment]
Is this layer index property working for anybody else?

**Comment by dmlitvinov** [comment]
We have exactly the same problem. There is no error without specifying an index, but there is no way to set the correct layer order

**Comment by anfriis** [comment]
I just stumbled across the same issue - but only on iOS. 
Android is fine with setting the `layerIndex´ prop.

The crash seems to happen [here](https://github.com/mapbox/mapbox-gl-native/blob/9a42bdd7aea0f23e892f2874be6c18acf2b0f0ae/platform/darwin/src/MGLStyle.mm#L322). I don't know why the style apparently have no layers when running on iOS. I tried to set `layerIndex` after a delay when the map and all layers have rendered, but it crashes immediately when setting the prop.

As a workaround, I used the `aboveLayerID` (`belowLayerId` could be used as well I suppose), for all my layers, even though they are not in the same `ShapeSource` and that works fine for both iOS and Android.

**Comment by anfriis** [comment]
I tried #361 in my project with setting `layerIndex` instead of `aboveLayerId`. 
The layers in my map style (street names, etc.) are placed rather high up with the highest being around `layerIndex` 40-42. 
I want my own layers to be placed above all the map's own layers, so if I set `layerIndex` to 50 for my own layer, I get:
`Terminating app due to uncaught exception 'NSRangeException', reason: 'Cannot insert style layer at out-of-bounds index 50.`
I have 14 layers on my map, so I have to use the 8 indexes between 42 and 50, and rely on `aboveLayerId` layers in the same `ShapeSource`. 

Does anyone know why it is not possible to use an index >= 50?
