### ISSUE TITLE
How to modify features in place?

### ISSUE THREAD

**Issue by jbeuckm** [react-native-mapbox-gl/maps#997]
I need to modify the properties data of in-place features from a vector tileset. We currently set style expressions but they can be quite large and affect performance (eg. a match expression on a list of 1000 ids). Better to have a static style and modify properties in the data.

Feature data can be modified directly: https://docs.mapbox.com/ios/maps/examples/runtime-animate-line/

A nice to have would be a function that replaces or merges the properties of a set of features by feature id.
```
const featureUpdates = {
   <featureId1>:{name:"New Name 1", data:"new data 1"},
   <featureId2>:{name:"New Name 2", data:"new data 2"}
}

this._map.modifyRenderedFeaturesProperties(featureUpdates, ['layerId'])

```

and/or

```
this._map.setPropertyOnFeatures("propertyName", propertyValue, [<featureId1>,<featureId2>], ['layerId'])
```

**Comment by ClayC-WeatherBug** [comment]
Does the other data you are wanting to add or modify to the features need to be part of their properties? I've done similar things to this and just kept a separate object or array of objects for lookups as needed. What I mean by this is maybe you have something like a vector source that provides just IDs but you have a separate API call or something that gets your property data for each ID so that when you need it (i.e. when opening a callout or something) it is available for you still but not pulled as part of the vector set.

**Comment by jbeuckm** [comment]
I want to modify properties to affect rendering of the feature in the map. As it is, when we want to change a render property, we rebuild the array of features and send it over the RN bridge. It would be more performant to send just the "diff" over the bridge and have native code make the change without having to ship and rerender the entire feature list.

**Comment by ClayC-WeatherBug** [comment]
Okay, so just to make sure I'm following let's talk about a simple example. Maybe you have a list of features that just contain lat/lng and their properties have a unique `id` value. You display these features as points on the map, and if a user taps one then you want to mark it as being currently selected so instead of showing the default icon you show the icon in a different color. At this point you have a style that basically just says "here is my icon for unselected" but when they select it you want to change the style property for that selected feature to say "here is the icon now". I know that this is probably waaaay more simplified than your real world use case, but does this align with what you are trying to get at? 

Right now you'd have to do something like a separate symbol layer with a different layer style and filter on the id of your features so that the style updates. You want to be able to just say "change the style on that particular feature to this." Does that all sound right?

**Comment by ferdicus** [comment]
@jbeuckm, could you maybe share more of your setup - I think that would help to get more context
Thanks 🙇

**Comment by mattijsf** [comment]
This question is similar to https://github.com/react-native-mapbox-gl/maps/issues/875

Unfortunately update vector tile data is not possible. The upstream libraries don't support it yet: https://github.com/mapbox/mapbox-gl-native/issues/12413

**Comment by king-d-dev** [comment]
@mattijsf  i think the support for feature state has been added to the upstream native libraries. Confirm from this comment here https://github.com/mapbox/mapbox-gl-native/issues/12413#issuecomment-809590260

**Comment by mattijsf** [comment]
Yes it is now possible with v10 sdk:
https://docs.mapbox.com/ios/maps/api/10.4.0/Classes/MapboxMap.html#/Feature%20State
https://docs.mapbox.com/android/maps/api/10.4.0/mapbox-maps-android/com.mapbox.maps/-mapbox-map/#%5Bcom.mapbox.maps%2FMapboxMap%2FsetFeatureState%2F%23kotlin.String%23kotlin.String%3F%23kotlin.String%23com.mapbox.bindgen.Value%2FPointingToDeclaration%2F%5D%2FFunctions%2F1040663990

@mfazekas I haven't been up-to-date with the v10 development but I think this should be fairly easy to add right? I might add it but the reality is that I don't have much time nowadays so it can take a while.

**Comment by mfazekas** [comment]
@mattijsf yes for v10 versions it shouldn't be hard to implement
